import React, { useState } from 'react';
import { Twitter, Linkedin } from 'lucide-react';

const Layout = () => {
  const [activeSection, setActiveSection] = useState('home');

  const navItems = [
    { id: 'home', label: 'Home' },
    { id: 'projects', label: 'Projects' },
    { id: 'writing', label: 'Writing' },
    { id: 'technical-writing', label: 'Technical Writing' },
    { id: 'reading', label: 'Reading' },
  ];

  const contentMap = {
    home: (
      <div className="space-y-8">
        <section>
          <p className="text-lg leading-relaxed">
            I've spent the last few years at the Georgia Institute of Technology studying Computer Science. I think the field exhibits a unique beauty - it is intensely interdisciplinary and applicable in almost every context. I like to think of it as one of the most straightforward ways to understand the rules that govern our lives, with significantly more to offer than just learning one or more of {'{Java, Python, C, etc.}'}.
          </p>
          <p className="text-lg leading-relaxed mt-4">
            Broadly, I'm interested in reasoning about the world around us. For me, this manifests in several ways.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-light mb-4">Work</h2>
          <p className="text-lg leading-relaxed">
            Currently, I study the applications of machine learning methods to science, focusing on biological contexts, with Dr. Amirali Aghazadeh.
          </p>
          <p className="text-lg leading-relaxed mt-4">In the past, I have worked on:</p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Partner Integrations at Box</li>
            <li>Decision Making for Autonomous Robots with Dr. Ye Zhao</li>
            <li>I enjoy working on problems and goals that force me to learn, beyond just technical skills.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-3xl font-light mb-4">Not Work</h2>
          <ul className="list-disc pl-5 space-y-4">
            <li>I try to spend much of my free time reading. I believe most questions you could have in life have been asked and answered many times before, and I try to find answers of my own whether it's in history books, biographies, fiction, or even academic papers/textbooks.</li>
            <li>One day I hope to teach when I am able. Few things are more beautiful than helping impart knowledge to someone that is hungry for it.</li>
            <li>What is the brain, really? Are we just functions generated by hundreds of years of evolution, fine-tuned by our lived experience?</li>
            <li>I have always believed in the existence of a soul, something more than our base instincts. Can we rigorously prove that such a thing exists?</li>
          </ul>
        </section>
      </div>
    ),
    projects: <p className="text-lg leading-relaxed">blah blah blah</p>,
    writing: <p className="text-lg leading-relaxed">blah blah blah</p>,
    'technical-writing': <p className="text-lg leading-relaxed"> blah blah blah </p>,
    reading: <p className="text-lg leading-relaxed">blah blah blah</p>,
  };

  return (
    <div className="min-h-screen flex flex-col bg-white p-8 font-serif">
      {/* Header with Navigation */}
      <header className="mb-24 w-full">
        <nav className="flex-grow">
          <ul className="flex justify-between items-center">
            {navItems.map((item) => (
              <li key={item.id}>
                <button
                  onClick={() => setActiveSection(item.id)}
                  className={`text-xl transition-colors focus:outline-none
                    ${activeSection === item.id
                      ? 'text-black font-semibold'
                      : 'text-gray-400 hover:text-gray-600'
                    }`}
                >
                  {item.label}
                </button>
              </li>
            ))}
          </ul>
        </nav>
      </header>

      {/* Main Content */}
      <main className="flex-grow flex flex-col items-start justify-center px-4">
        {activeSection === 'home' && (
          <h1 className="text-5xl font-light mb-8 tracking-wide">Aryan Musharaf</h1>
        )}
        <div className="prose prose-lg w-full max-w-none">
          {contentMap[activeSection]}
        </div>
      </main>

      {/* Footer with Social Links */}
      <footer className="mt-16 flex justify-center space-x-6">
        <a href="https://twitter.com/aryanmusharaf" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-blue-400 transition-colors">
          <Twitter size={24} />
          <span className="sr-only">Twitter</span>
        </a>
        <a href="https://linkedin.com/in/aryanmusharaf" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-blue-700 transition-colors">
          <Linkedin size={24} />
          <span className="sr-only">LinkedIn</span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;