import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { Linkedin, X, Mail} from 'lucide-react';

const Layout = () => {
  const [activeSection, setActiveSection] = useState('home');

  const navItems = [
    { id: 'home', label: 'Home' },
    { id: 'projects', label: 'Projects' },
    { id: 'writing', label: 'Writing' },
    { id: 'technical-writing', label: 'Technical Writing' },
    { id: 'reading', label: 'Reading' },
  ];


  const contentMap = {
    home: (
      <div className="space-y-8">
        <section>
          <p className="text-[14px] leading-relaxed">
            I've spent the last few years at the Georgia Institute of Technology studying Computer Science. Broadly, I'm interested in reasoning about the world around us. For me, this manifests in several ways:
          </p>
        </section>

        <section>
          <h2 className="text-xl font-light mb-4">Work</h2>
          <p className="text-[14px] leading-relaxed">
            Currently, I study the applications of machine learning methods to science, focusing on biological contexts, with Amirali Aghazadeh. In the past, I have worked on:
          </p>
          <ul className="list-disc text-[14px] leading-relaxed pl-5 space-y-2 mt-2">
            <li>Partner Integrations at Box</li>
            <li>Decision Making for Autonomous Robots with Ye Zhao</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-light mb-4">Not Work</h2>
          <ul className="list-disc text-[14px] leading-relaxed pl-5 space-y-4">
            <li>I try to spend a lot of my free time reading. I think most questions you could have in life have been asked and answered many times before, and I try to find answers of my own whether it's in history books, biographies, fiction, or even academic papers/textbooks.</li>
            <li>One day I hope to teach when I am able. Few things are more beautiful than helping impart knowledge to someone that is hungry for it.</li>
            <li>What is the brain, really? Are we just functions generated by hundreds of years of evolution, fine-tuned by our lived experience?</li>
            <li>I have always believed in the existence of a soul, something more than our base instincts. Can we rigorously prove that such a thing exists?</li>
          </ul>
        </section>
      </div>
    ),
    projects: <p className="text-lg leading-relaxed">More to come!</p>,
    writing: <p className="text-lg leading-relaxed">More to come!</p>,
    'technical-writing': <p className="text-lg leading-relaxed">More to come!</p>,
  };

  return (
    <div className="min-h-screen flex flex-col bg-white p-2 font-serif">
      <Helmet>
        <title>Aryan</title>
      </Helmet>
      
      <div className="flex flex-grow max-w-5xl mx-auto w-full">
        {/* Left column with main content */}
        <main className="w-3/4 pr-8">
          {activeSection === 'home' && (
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-light mb-12 tracking-wide">
              Aryan Musharaf
            </h1>
          )}
          <div className="prose prose-sm sm:prose-base space-y-4">
            {contentMap[activeSection]}
          </div>
        </main>

        {/* Right column with navbar */}
        <nav className="w-1/4 pt-8">
          <ul className="space-y-2">
            {navItems.map((item) => (
              <li key={item.id}>
                <button
                  onClick={() => setActiveSection(item.id)}
                  className={`text-lg transition-colors focus:outline-none w-full text-left
                    ${activeSection === item.id
                      ? 'text-black font-semibold'
                      : 'text-gray-400 hover:text-gray-600'
                    }`}
                >
                  {item.label}
                </button>
              </li>
            ))}
          </ul>
        </nav>
      </div>

      {/* Footer with Social Links */}
      <footer className="mt-6 flex justify-center space-x-4">
        <a href="https://x.com/aryanmusharaf" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-blue-400 transition-colors">
          <X size={24} />
          <span className="sr-only">X</span>
        </a>
        <a href="mailto:aryanmusharaf11@gmail.com" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-red-500 transition-colors">
          <Mail size={24} />
          <span className="sr-only">Email</span>
        </a>
        <a href="https://linkedin.com/in/aryanmusharaf" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-blue-700 transition-colors">
          <Linkedin size={24} />
          <span className="sr-only">LinkedIn</span>
        </a>
      </footer>

    </div>
  );
};

export default Layout;